# Generated by Django 6.0.6 on 2026-06-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_genre_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='inStock',
            new_name='stockAmount',
        ),
    ]
